
name: Digger Workflow

on:
  workflow_dispatch:
    inputs:
      spec:
        required: true
      run_name:
        required: false

run-name: ${{inputs.run_name}}

jobs:
  digger-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # required to merge PRs
      actions: write       # required for plan persistence
      id-token: write      # required for workload-identity-federation
      pull-requests: write # required to post PR comments
      statuses: write      # required to validate combined PR status
      issues: write

    steps:
      - name: ${{ fromJSON(github.event.inputs.spec).job_id }}
        run: echo "job id ${{ fromJSON(github.event.inputs.spec).job_id }}"
      - uses: actions/checkout@v4

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}      

      - name: digger
        uses: diggerhq/digger@feat/cache-dependencies-s3-prefix
        with:
          digger-spec: ${{ inputs.spec }}
          digger-private-key: ${{ secrets.DIGGER_PRIVATE_KEY }}
          setup-aws: true
          disable-locking: true
          setup-opentofu: true
          setup-terraform: true
          cache-dependencies-s3: true
          cache-dependencies-s3-bucket: terraform-cache-1756322349465
          cache-dependencies-s3-bucekt-prefix: cache
          cache-dependencies-s3-region: us-east-1
          # local-dev-mode: true
          # local-dev-cli-path: /Users/mohamedsayed/dev/digger/digger/cli
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
